//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextRedactor {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.0.0")]
    internal sealed partial class TextRedactorSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static TextRedactorSettings defaultInstance = ((TextRedactorSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TextRedactorSettings())));
        
        public static TextRedactorSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SettingPathToProjectFolder {
            get {
                return ((string)(this["SettingPathToProjectFolder"]));
            }
            set {
                this["SettingPathToProjectFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentStateProjectBrowserProjects {
            get {
                return ((string)(this["CurrentStateProjectBrowserProjects"]));
            }
            set {
                this["CurrentStateProjectBrowserProjects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SettingFontSize {
            get {
                return ((string)(this["SettingFontSize"]));
            }
            set {
                this["SettingFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public string SettingMarginWight {
            get {
                return ((string)(this["SettingMarginWight"]));
            }
            set {
                this["SettingMarginWight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string SettingLineSpacing {
            get {
                return ((string)(this["SettingLineSpacing"]));
            }
            set {
                this["SettingLineSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public string SettingFont {
            get {
                return ((string)(this["SettingFont"]));
            }
            set {
                this["SettingFont"] = value;
            }
        }
    }
}
